networks:
  whatsapp:
    driver: bridge

services:
  go-whatsapp-multi-session-rest-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'go-whatsapp-multi-session-rest-api:latest'
    container_name: 'go-whatsapp-multi-session-rest-api'
    networks:
      - whatsapp
    ports:
      - "7001:7001"
    env_file:
      - ./.env
    environment:
      - TZ=UTC
    volumes:
      - ./dbs:/usr/app/gowam-rest/dbs
      - ./docs:/usr/app/gowam-rest/docs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
